const express = require('express');
const requireAuth = require('../middleware/requireAuth');
const RecommendationEngine = require('../services/RecommendationEngine');
const PlaylistIntelligence = require('../services/PlaylistIntelligence');
const { parseIntent } = require('../services/PlaylistIntentEngine');

const router = express.Router();
router.use(requireAuth);

/**
 * @route GET /api/recommendations/daily-mix
 * @desc Get a personalized mix for the authenticated user
 */
router.get('/daily-mix', async (req, res) => {
  try {
    const songs = await RecommendationEngine.getDailyMix(req.userId);
    res.json({
      id: 'daily-mix',
      title: 'Daily Mix',
      description: 'Made for you.',
      thumbnailUrl: songs.length > 0 ? songs[0].thumbnailUrl : '',
      songs,
    });
  } catch (error) {
    console.error('Daily Mix route error:', error.message);
    res.status(500).json({ error: 'Failed to generate recommendations' });
  }
});

/**
 * @route GET /api/recommendations/radio/song/:id
 * @desc Get a radio queue from a seed song. Supports session context via query params.
 */
router.get('/radio/song/:id', async (req, res) => {
  try {
    // Parse optional session context from query string
    // e.g. ?recentArtists=Arijit+Singh,Taylor+Swift&recentIds=songId1,songId2
    const recentArtists = req.query.recentArtists
      ? req.query.recentArtists.split(',').map(s => s.trim())
      : [];
    const recentSongIds = req.query.recentIds
      ? req.query.recentIds.split(',').map(s => s.trim())
      : [];

    const sessionContext = { recentArtists, recentSongIds };
    const songs = await RecommendationEngine.getSongRadio(
      req.params.id, req.userId, 15, sessionContext
    );
    res.json(songs);
  } catch (error) {
    console.error('Song Radio route error:', error.message);
    res.status(500).json({ error: 'Failed to generate radio' });
  }
});

/**
 * @route GET /api/recommendations/radio/artist/:name
 * @desc Get a radio stream for an artist
 */
router.get('/radio/artist/:name', async (req, res) => {
  try {
    const songs = await RecommendationEngine.getArtistRadio(req.params.name, req.userId);
    res.json(songs);
  } catch (error) {
    console.error('Artist Radio route error:', error.message);
    res.status(500).json({ error: 'Failed to generate artist radio' });
  }
});

/**
 * @route GET /api/recommendations/one-song-away
 * @desc Get a single high-confidence discovery track
 */
router.get('/one-song-away', async (req, res) => {
  try {
    const song = await RecommendationEngine.getOneSongAway(req.userId);
    if (!song) return res.status(404).json({ error: 'No discovery track found right now' });
    res.json(song);
  } catch (error) {
    console.error('One Song Away route error:', error.message);
    res.status(500).json({ error: 'Failed to fetch discovery track' });
  }
});

/**
 * @route POST /api/recommendations/playlist
 * @desc Generate a playlist from a natural language intent or playlist config.
 *       Body: { intent: string | object, targetCount?: number, debug?: boolean }
 */
router.post('/playlist', async (req, res) => {
  try {
    const { intent, targetCount = 30, debug = false } = req.body;
    if (!intent) return res.status(400).json({ error: 'Missing intent field' });

    const result = await PlaylistIntelligence.generate(intent, req.userId, {
      targetCount,
      debugMode: debug,
      forceRefresh: true,
    });

    res.json({
      id: 'custom-playlist',
      title: typeof intent === 'string' ? intent : (intent.title || 'Custom Playlist'),
      description: 'Generated by Amplify Intelligence',
      songs: result.songs,
      meta: result.meta,
    });
  } catch (error) {
    console.error('Playlist generation error:', error.message);
    res.status(500).json({ error: 'Failed to generate playlist' });
  }
});

/**
 * @route POST /api/recommendations/next
 * @desc Get the next batch of tracks for dynamic autoplay.
 *       Body: { currentSong: Track, sessionHistory: string[], sessionArtists: string[] }
 */
router.post('/next', async (req, res) => {
  try {
    const { currentSong, sessionHistory = [], sessionArtists = [] } = req.body;
    if (!currentSong) return res.status(400).json({ error: 'Missing currentSong' });

    const sessionContext = {
      recentSongIds: sessionHistory,
      recentArtists: sessionArtists,
    };

    const tracks = await PlaylistIntelligence.getRadioTracks(
      currentSong, sessionContext, req.userId, 8
    );
    res.json(tracks);
  } catch (error) {
    console.error('Next tracks error:', error.message);
    res.status(500).json({ error: 'Failed to get next tracks' });
  }
});

/**
 * @route POST /api/recommendations/similar
 * @desc Get tracks similar to a given song.
 *       Body: { song: Track }
 */
router.post('/similar', async (req, res) => {
  try {
    const { song } = req.body;
    if (!song) return res.status(400).json({ error: 'Missing song field' });

    const tracks = await PlaylistIntelligence.getSimilar(song, req.userId, 20);
    res.json(tracks);
  } catch (error) {
    console.error('Similar tracks error:', error.message);
    res.status(500).json({ error: 'Failed to get similar tracks' });
  }
});

/**
 * @route GET /api/recommendations/discover
 * @desc Get a personalised discovery playlist
 */
router.get('/discover', async (req, res) => {
  try {
    const result = await PlaylistIntelligence.discover(req.userId, 25);
    res.json({
      id: 'discover',
      title: 'Discover New Music',
      description: 'Songs you might not have heard yet.',
      thumbnailUrl: result.songs.length > 0 ? result.songs[0].thumbnailUrl : '',
      songs: result.songs,
    });
  } catch (error) {
    console.error('Discover error:', error.message);
    res.status(500).json({ error: 'Failed to generate discovery playlist' });
  }
});

module.exports = router;
